name: Deploy to Cloudflare Pages
on:
  push:
    branches: ["beta"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Pages
        run: |
          cp .github/404.html 404.html
          cp .github/beta.html index.html
          cp .github/discord.svg discord.svg
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=orangeblox-beta
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}